package uk.ac.cam.cl.dtg.isaac.dos;

public enum Hub {
  BIRMINGHAM_AND_CENTRAL_MIDLANDS,
  CAMBRIDGE_AND_NORTHAMPTONSHIRE,
  CHESHIRE,
  CORNWALL,
  CUMBRIA_SATELLITE,
  DARTFORD_AND_EAST_SUSSEX,
  DEVON,
  GLOUCESTERSHIRE_WILTSHIRE_AND_NORTH_SOMERSET,
  GREATER_MANCHESTER,
  LANCASHIRE_SATELLITE,
  LEICESTER_NOTTINGHAMSHIRE_AND_RUTLAND,
  LINCOLNSHIRE,
  LONDON_HERTFORDSHIRE_AND_ESSEX,
  LONDON_HERTFORDSHIRE_AND_HAMPSHIRE,
  LONDON_SURREY_AND_WEST_SUSSEX,
  MAIDSTONE_AND_KENT,
  MILTON_KEYNES_AND_NORTHAMPTONSHIRE,
  NEWCASTLE_DURHAM_AND_EAST_CUMBRIA,
  NORFOLK,
  NORTH_EAST_AND_NORTHUMBERLAND,
  NORTH_YORKSHIRE_LEEDS_AND_WAKEFIELD
}
