/**
 * Copyright 2020 Stephen Cummins
 * <br>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * <br>
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * <br>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.ac.cam.cl.dtg.isaac.dos.users;

import java.time.Instant;

/**
 * Immutable type to represent the secret generated by the API and sent to the client for MFA setup.
 */
public class TOTPSharedSecret {
  private Long userId;
  private String sharedSecret;
  private Instant created;
  private Instant lastUpdated;

  /**
   * New shared secret object.
   *
   * @param userId       - User id for traceability and can be checked by the frontend.
   * @param sharedSecret - secret string which is used by the TOTP algorithm
   * @param created      - created date.
   * @param lastUpdated  - last date this value was changed (not deleted).
   */
  public TOTPSharedSecret(final Long userId, final String sharedSecret, final Instant created,
                          final Instant lastUpdated) {
    this.userId = userId;
    this.sharedSecret = sharedSecret;
    this.created = created;
    this.lastUpdated = lastUpdated;
  }

  /**
   * Get the user id that the secret was generated for.
   */
  public Long getUserId() {
    return userId;
  }

  public String getSharedSecret() {
    return sharedSecret;
  }

  public Instant getCreated() {
    return created;
  }

  public Instant getLastUpdated() {
    return lastUpdated;
  }
}
