services:
  dev:
    image: maven:3.9.9-eclipse-temurin-11
    working_dir: /src/app
    command: sleep infinity
    volumes:
      - ./:/src/app

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - cluster.name=isaac
      - "network.host=0.0.0.0"
      - node.name=localhost
      - cluster.initial_master_nodes=localhost
      - http.max_content_length=512mb
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
    mem_limit: 6G

  postgres:
    container_name: postgres
    image: postgres:16
    volumes:
      - pg-local:/var/lib/postgresql/data
      - ./src/main/resources/db_scripts/postgres-rutherford-create-script.sql:/docker-entrypoint-initdb.d/00-isaac-create.sql:ro
      - ./src/main/resources/db_scripts/postgres-rutherford-functions.sql:/docker-entrypoint-initdb.d/01-isaac-functions.sql:ro
      - ./src/main/resources/db_scripts/quartz_scheduler_create_script.sql:/docker-entrypoint-initdb.d/02-isaac-quartz.sql:ro
    environment:
      POSTGRES_USER: rutherford
      POSTGRES_PASSWORD: rutherf0rd

volumes:
  pg-local:
