version: '2'
services:
  equality-checker:
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    logging:
      driver: journald
      options:
        tag: equality-checker
    restart: always
  chemistry-checker:
    container_name: chemistry-checker
    image: ucamcldtg/chemistry-checker
    restart: always

networks:
  default:
    external:
      name: isaac
volumes:
  pg-live:
    external: true
  pg-staging:
    external: true
  pg-dev:
    external: true
