# Note: When running locally in ubuntu in order for ElasticSearch to wrok 
# you will need to run 
# sysctl -w vm.max_map_count=262144
version: '2'
services:
  equality-checker:
    network_mode: bridge
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    ports:
      - "5000:5000"
  chemistry-checker:
    network_mode: bridge
    container_name: chemistry-checker
    image: ucamcldtg/chemistry-checker
    ports:
      - "5001:5000"
    volumes:
      - ../.m2:/root/.m2:rw
  elasticsearch:
    network_mode: bridge
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
      - ./elasticsearch-local.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200-9400:9200-9400"

  postgres:
    network_mode: bridge
    container_name: postgres
    image: isaac-pg
    ports:
      - "5432:5432"
  app-physics:
    network_mode: bridge
    container_name: app-physics
    image: nginx:1.13.12
    volumes:
      - "../isaac-app/app:/usr/share/nginx/html:ro"
      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8000:80"
  app-chemistry:
    network_mode: bridge
    container_name: app-chemistry
    image: nginx:1.13.12
    volumes:
      - "../isaac-app/app:/usr/share/nginx/html:ro"
      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8001:80"
  app-biology:
    network_mode: bridge
    container_name: app-biology
    image: nginx:1.13.12
    volumes:
      - "../isaac-app/app:/usr/share/nginx/html:ro"
      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8002:80"
networks:
  default:
    external:
      name: bridge
