# Note: When running locally in ubuntu in order for ElasticSearch to work, you will need to run:
# sysctl -w vm.max_map_count=262144

version: '2'
services:

  equality-checker:
    network_mode: bridge
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    ports:
      - "5000:5000"

  chemistry-checker-js:
    network_mode: bridge
    container_name: chemistry-checker-js
    image: ghcr.io/isaacphysics/chemistry-checker-js
    ports:
      - "5002:5002"

  elasticsearch:
    network_mode: bridge
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.9
    environment:
      - cluster.name=isaac
      - node.name=localhost
      - discovery.type=single-node
      - http.max_content_length=512mb
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.ml.enabled=false
    ports:
      - "9200:9200"
    mem_limit: 6G

  cs-elasticsearch:
    network_mode: bridge
    container_name: cs-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.9
    environment:
      - cluster.name=cs-isaac
      - node.name=localhost
      - discovery.type=single-node
      - http.max_content_length=512mb
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.ml.enabled=false
    ports:
      - "9201:9200"
    mem_limit: 6G

  it-elasticsearch:
    network_mode: bridge
    container_name: it-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.9
    environment:
      - cluster.name=it-isaac
      - node.name=localhost
      - discovery.type=single-node
      - http.max_content_length=512mb
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.ml.enabled=false
    ports:
      - "9501:9200"
    mem_limit: 6G

  postgres:
    network_mode: bridge
    container_name: postgres
    image: postgres:16
    volumes:
      - pg-local:/var/lib/postgresql/data
      - ./src/main/resources/db_scripts/postgres-rutherford-create-script.sql:/docker-entrypoint-initdb.d/00-isaac-create.sql:ro
      - ./src/main/resources/db_scripts/postgres-rutherford-functions.sql:/docker-entrypoint-initdb.d/01-isaac-functions.sql:ro
      - ./src/main/resources/db_scripts/quartz_scheduler_create_script.sql:/docker-entrypoint-initdb.d/02-isaac-quartz.sql:ro
    environment:
      POSTGRES_USER: rutherford
      POSTGRES_PASSWORD: rutherf0rd
    ports:
      - "5432:5432"

  it-postgres:
    network_mode: bridge
    container_name: it-postgres
    image: postgres:16
    volumes:
      - ./src/main/resources/db_scripts/postgres-rutherford-create-script.sql:/docker-entrypoint-initdb.d/00-isaac-create.sql:ro
      - ./src/main/resources/db_scripts/postgres-rutherford-functions.sql:/docker-entrypoint-initdb.d/01-isaac-functions.sql:ro
      - ./src/main/resources/db_scripts/quartz_scheduler_create_script.sql:/docker-entrypoint-initdb.d/02-isaac-quartz.sql:ro
      - ./src/test/resources/test-postgres-rutherford-data-dump.sql:/docker-entrypoint-initdb.d/03-isaac-test-data.sql:ro
    environment:
      POSTGRES_USER: rutherford
      POSTGRES_PASSWORD: rutherf0rd
    ports:
      - "5433:5432"

#  app-physics:
#    network_mode: bridge
#    container_name: app-physics
#    image: nginx:stable
#    volumes:
#      - "../isaac-app/app:/usr/share/nginx/html:ro"
#      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
#    ports:
#      - "8000:80"

networks:
  default:
    external:
      name: bridge

volumes:
  pg-local:
    external: true
