version: '2'
services:
  router:
    container_name: isaac-router
    image: nginx:1.9.11
    ports:
      - "80:80"
    volumes:
      - /local/data/nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    external:
      name: isaac
