version: '2'
services:
  equality-checker:
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    restart: always
  es-tracking:
    container_name: es-tracking
    image: elasticsearch:1.4
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    restart: always
  es-live:
    container_name: es-live
    image: elasticsearch:1.4
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    restart: always
  pg-live:
    container_name: pg-live
    image: isaac-pg
    volumes:
      - pg-live:/pgdata
    restart: always
  pg-staging:
    container_name: pg-staging
    image: isaac-pg
    volumes:
      - pg-staging:/pgdata
    restart: always
  pg-dev:
    container_name: pg-dev
    image: isaac-pg
    volumes:
      - pg-dev:/pgdata
    restart: always
networks:
  default:
    external:
      name: isaac
volumes:
  pg-live:
    external: true
  pg-staging:
    external: true
  pg-dev:
    external: true
