version: '2'
services:

  equality-checker:
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    restart: unless-stopped

  chemistry-checker:
    container_name: chemistry-checker
    image: ucamcldtg/chemistry-checker
    restart: unless-stopped

  chemistry-checker-js:
    container_name: chemistry-checker-js
    image: ghcr.io/isaacphysics/chemistry-checker-js
    restart: unless-stopped

networks:
  default:
    external:
      name: isaac
