# Note: When running locally in ubuntu in order for ElasticSearch to wrok 
# you will need to run 
# sysctl -w vm.max_map_count=262144
version: '2'
services:
  equality-checker:
    network_mode: bridge
    container_name: equality-checker
    image: ucamcldtg/equality-checker
    ports:
      - "5000:5000"
  chemistry-checker:
    network_mode: bridge
    container_name: chemistry-checker
    image: ucamcldtg/chemistry-checker
    ports:
      - "5001:5000"
    volumes:
      - ../.m2:/root/.m2:rw
  elasticsearch:
    network_mode: bridge
    container_name: elasticsearch
    image: elasticsearch:5.0.1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200-9400:9200-9400"

  kafka:
    network_mode: bridge
    container_name: kafka
    image: ucamcldtg/kafka-standalone
    links:
      - zookeeper:zookeeper
    build:
      context: ./kafka
      dockerfile: Dockerfile-kafka
    volumes:
#      - ../kafka-data:/kafka-data:rw
      - ./kafka/server.properties.local:/opt/kafka/config/server.properties:ro
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    network_mode: bridge
    container_name: zookeeper
    image: ucamcldtg/zookeeper-standalone
    build:
      context: ./kafka
      dockerfile: Dockerfile-zookeeper
    volumes:
#      - ../zookeeper-data:/zookeeper-data:rw
      - ./kafka/zoo.cfg:/opt/zookeeper/conf/zoo.cfg:ro

  postgres:
    network_mode: bridge
    container_name: postgres
    image: isaac-pg
    ports:
      - "5432:5432"
  app-physics:
    network_mode: bridge
    container_name: app-physics
    image: nginx:1.9.11
    volumes:
      - "../isaac-app/app:/usr/share/nginx/html:ro"
      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8000:80"
  app-chemistry:
    network_mode: bridge
    container_name: app-chemistry
    image: nginx:1.9.11
    volumes:
      - "../isaac-app/app:/usr/share/nginx/html:ro"
      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8001:80"
  app-biology:
    network_mode: bridge
    container_name: app-biology
    image: nginx:1.9.11
    volumes:
      - "../isaac-app/app:/usr/share/nginx/html:ro"
      - "../isaac-app/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8002:80"
networks:
  default:
    external:
      name: bridge
