FROM isaac-api-base:latest AS target

COPY . /isaac-api

# build isaac api war file without unit tests
RUN mvn package -Dmaven.test.skip=true

# create clean jetty docker container
FROM jetty:11.0.20-jdk17-eclipse-temurin AS server
USER root
ADD resources/school_list_2022.tar.gz /local/data/
COPY --from=target /isaac-api/target/isaac-api.war /var/lib/jetty/webapps/isaac-api.war
RUN chmod 755 /var/lib/jetty/webapps/*
RUN chown jetty /var/lib/jetty/webapps/*

COPY resources/jetty.xml /usr/local/jetty/etc/
COPY resources/start.ini /var/lib/jetty/

# prepare things so that jetty runs in the docker entrypoint
USER jetty
WORKDIR $JETTY_BASE
