FROM isaac-api-base:latest as target

COPY . /isaac-api

# build isaac api war file without unit tests
RUN mvn package -Dmaven.test.skip=true -P etl

# create clean jetty docker container
FROM jetty:9.3.27 as server
USER root
COPY --from=target /isaac-api/target/isaac-api.war /var/lib/jetty/webapps/isaac-api.war
RUN chmod 755 /var/lib/jetty/webapps/*
RUN chown jetty /var/lib/jetty/webapps/*

#RUN sed -i -e 's#dev/random#dev/./urandom#g' $JAVA_HOME/jre/lib/security/java.security

# prepare things so that jetty runs in the docker entrypoint
USER jetty
WORKDIR $JETTY_BASE