package uk.ac.cam.cl.dtg.segue.auth;

import java.io.IOException;

/**
 * This interface defines the required methods for an oauth 1 or oauth 2 provider
 * 
 * @author nr378
 */
public interface IOAuthAuthenticator extends IFederatedAuthenticator {
	/**
	 * Step 2 of OAUTH - Get authorisation code from oauth provider using the
	 * response URL they have provided.
	 * 
	 * @param url
	 *            containing the authorisation code
	 * @return the extracted authorisation code.
	 * @throws IOException
	 */
	String extractAuthCode(String url) throws IOException;

	/**
	 * Step 3 of OAUTH - Exchange short term authorisation code for an access
	 * token which can be used to authenticate the user.
	 * 
	 * This method will contact the oauth provider directly to exchange the
	 * authorisation code for a token.
	 * 
	 * This method returns an internal reference which will allow it to look up
	 * the 3rd party token. e.g. if you call an IFederatedAuthenticator method
	 * getUserDetails - it will require this internal reference.
	 * 
	 * @param authorizationCode
	 *            as provided by the getAuthCode method.
	 * @return String containing a reference number generated by this
	 *         IOAuth2Authenticator that allows us to use
	 *         FederatedAuthentication methods that require an internal
	 *         reference number.
	 * @throws IOException
	 *             , CodeExchangeException, NoUserIdException
	 */
	String exchangeCode(String authorizationCode) throws IOException,
			CodeExchangeException, NoUserIdException;
}
